services:
  backend:
    container_name: "zwalletbe"
    # image buatan
    image: zikrigusli/zwalletapi:1
    ports:
      - "3001:3000"
    # .env akan ditimpa dengan envirotment dibawah
    environment:
      - DB_HOST=postgres
    networks:
      - gonet

networks:
  gonet:
    name: "coba"
    # eksternal true menandakan bahwa network sudah ada, tidak perlu buat lagi
    external: true
# docker compose up -d
# docker compose down
